FROM eclipse-temurin:17-jdk-focal
VOLUME /tmp
ADD target/filesta-0.0.1-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]